### PR TITLE
Fixed search for new kickass markup

### PR DESCRIPTION
**Pull request by arrowcircle**
Kickass torrents changed markup and I fixed gem to use new markup. I also bumped version.
Please merge and release.

### CODE REVIEW

**Comment by fissionxuiptz** [comment]
Thanks for this!

**Comment by arrowcircle** [comment]
@fissionxuiptz Please release new version to rubygems

**Comment by fissionxuiptz** [comment]
Already done. If you're not seeing kat update you might still have your dev version installed.

**Comment by arrowcircle** [comment]
@fissionxuiptz I dont see releaes in github. But in ruby gems all seems to be ok. Thank you

**Pull request merged**
